alignment_name: 'mammal_set'
refName: simHuman_chr6

species:
  - simCow_chr6
  - simDog_chr6
  - simMouse_chr6
  - simRat_chr6

speciesTree: "((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974):0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303):0.032898);"

cactus_sif: 'docker://quay.io/comparative-genomics-toolkit/cactus:v2.5.1'
# the bind-path list needs to start with a ',' to be appended properly
singularity_bind_paths: ''
cactus_cores: "4"
